/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2015-06-16 15:49:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mobiles_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link rel=\"stylesheet\" href=\"http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css\">\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>SecondHand</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".menu {\n");
      out.write("\tfloat: none;\n");
      out.write("\theight: 80px;\n");
      out.write("}\n");
      out.write(".account {\n");
      out.write("\tposition: absolute;\n");
      out.write("\ttop: 25px;\n");
      out.write("\tright: 289px;\n");
      out.write("}\n");
      out.write(".user1 {\n");
      out.write("\tposition: absolute;\n");
      out.write("\ttop: 31px;\n");
      out.write("\tright: 410px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class = \"well well-lg menu\">\n");
      out.write("<form action = \"SearchController\">\n");
      out.write("<table align = \"right\">\n");
      out.write("<tr>\n");
      out.write("<td>\n");
      out.write("<div class = \"pull-right\">\n");
      out.write("<div class=\"dropdown\">\n");
      out.write("    <input name = \"item\" class = \"dropdown-toggle\" data-toggle=\"dropdown\"><span class=\"caret\"></span>\n");
      out.write("    <ul class=\"dropdown-menu\">\n");
      out.write("      <li><a tabindex=\"-1\" href=\"show.jsp?category=Mobile\">Mobiles</a></li>\n");
      out.write("      <li><a tabindex=\"-1\" href=\"show.jsp?category=RealEstate\">Real Estate</a></li>\n");
      out.write("      <li><a tabindex=\"-1\" href=\"show.jsp?category=Books\">Books</a></li>\n");
      out.write("      <li class=\"divider\"></li>\n");
      out.write("      <li><a tabindex=\"-1\" href=\"productdisplay.jsp\">All Categories</a></li>\n");
      out.write("    </ul>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</td>\n");
      out.write("<td>&nbsp;</td>\n");
      out.write("<td><button type=\"submit\" class=\"btn btn-xs btn-success\"><span class = \"glyphicon glyphicon-search\" style = \"color: white; font-size: 29px;\"></span></button></td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("</form>\n");
      out.write("<a href = \"login.jsp\">\n");
      out.write("<span class = \"glyphicon glyphicon-user user1\" style = \"color: blue; font-size: 22px;\"></span>\n");
      out.write("<p class = \"account\" style = \"font-size: 22px; color: blue;\">My Account</p>\n");
      out.write("</a>\n");
      out.write("</div>\n");
      out.write("    <div class=\"col-md-3\">\n");
      out.write("      <ul class=\"nav nav-pills nav-stacked\">\n");
      out.write("        <li  class=\"active\"><a href=\"mobiles.jsp\">Mobiles and Tablets</a></li>\n");
      out.write("        <li><a href=\"electronics.jsp\">Electronics and Appliances</a></li>\n");
      out.write("        <li><a href=\"vehicles.jsp\">Vehicles</a></li>\n");
      out.write("        <li><a href=\"home.jsp\">Home & Furniture</a></li>\n");
      out.write("        <li><a href=\"animals.jsp\">Animals</a></li>\n");
      out.write("        <li><a href=\"books.jsp\">Books, Sports & Hobbies</a></li>\n");
      out.write("        <li><a href=\"fashion.jsp\">Fashion & Beauty</a></li>\n");
      out.write("        <li><a href=\"kids.jsp\">Kids & Baby Products</a></li>\n");
      out.write("        <li><a href=\"services.jsp\">Services</a></li>\n");
      out.write("        <li><a href=\"jobs.jsp\">Jobs</a></li>\n");
      out.write("        <li><a href=\"realestate.jsp\">Real Estate</a></li>\n");
      out.write("      </ul>\n");
      out.write("    </div> \n");
      out.write("<h3>Mobiles and Tablets</h3>\n");
      out.write("<hr>\n");
      out.write("<div>\n");
      out.write("<table>\n");
      out.write("<tr>\n");
      out.write("\t<td>\n");
      out.write("\t\t<img src = \"./IMG/mobile.png\" style = \"width: 140px; height: 120px;\">\n");
      out.write("\t\t<br> <br>\n");
      out.write("\t\t<h4 align=\"center\">Mobiles</h4>\n");
      out.write("\t</td>\n");
      out.write("\t<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>\n");
      out.write("\t<td>\n");
      out.write("\t\t<img src = \"./IMG/tablet.png\" style = \"width: 140px; height: 120px;\">\n");
      out.write("\t\t<br> <br>\n");
      out.write("\t\t<h4 align=\"center\">Tablets</h4>\n");
      out.write("\t</td>\n");
      out.write("\t<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>\n");
      out.write("\t<td>\n");
      out.write("\t\t<img src = \"./IMG/earphones.png\" style = \"width: 140px; height: 120px;\">\n");
      out.write("\t\t<br> <br>\n");
      out.write("\t\t<h4 align=\"center\">Ear Phones</h4>\n");
      out.write("\t</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("\t<td>\n");
      out.write("\t\t<img src = \"./IMG/casecover.png\" style = \"width: 140px; height: 120px;\">\n");
      out.write("\t\t<br> <br>\n");
      out.write("\t\t<h4 align=\"center\">Case Covers</h4>\n");
      out.write("\t</td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("</div>   \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
