/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2015-06-17 11:29:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class start_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('	');

	HttpSession hs = request.getSession();
	String email = (String) hs.getAttribute("emailid");
	
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\">\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js\"></script>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Second Hand</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".menu {\n");
      out.write("\tfloat: none;\n");
      out.write("\theight: 80px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".account {\n");
      out.write("\tposition: absolute;\n");
      out.write("\ttop: 25px;\n");
      out.write("\tright: 289px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".user1 {\n");
      out.write("\tposition: absolute;\n");
      out.write("\ttop: 31px;\n");
      out.write("\tright: 410px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".tablediv {\n");
      out.write("\theight: 00px;\n");
      out.write("\twidth: 800px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logo {\n");
      out.write("\tposition: absolute;\n");
      out.write("\ttop: 20px;\n");
      out.write("\tleft: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".submitbtn {\n");
      out.write("\tposition: absolute;\n");
      out.write("\ttop: 26px;\n");
      out.write("\tleft: 730px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"logo\">\n");
      out.write("\t\t<img src=\"./IMG/logo.PNG\" style=\"width: 220px; height: 160px;\">\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"submitbtn\">\n");
      out.write("\t\t<a href=\"submitanad.jsp\"><button type=\"button\"\n");
      out.write("\t\t\t\tclass=\"btn btn-primary btn-md\">Submit An Ad</button></a>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"well well-lg menu\">\n");
      out.write("\t\t<form action=\"SearchController\">\n");
      out.write("\t\t\t<table align=\"right\">\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<!-- <td><input name = \"item\" type = \"text\" placeholder = \"What are you looking for?\" style = \"width: 200px; height: 35px;\"></td> -->\n");
      out.write("\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t<div class=\"pull-right\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown\">\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"item\" class=\"dropdown-toggle\"\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-toggle=\"dropdown\"><span class=\"caret\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a tabindex=\"-1\" href=\"show.jsp?category=Mobile\">Mobiles</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a tabindex=\"-1\" href=\"show.jsp?category=RealEstate\">Real\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tEstate</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a tabindex=\"-1\" href=\"show.jsp?category=Books\">Books</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"divider\"></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a tabindex=\"-1\" href=\"mobiles.jsp\">All Categories</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t<td>&nbsp;</td>\n");
      out.write("\t\t\t\t\t<td><button type=\"submit\" class=\"btn btn-xs btn-success\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-search\"\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"color: white; font-size: 29px;\"></span>\n");
      out.write("\t\t\t\t\t\t</button></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t</form>\n");
      out.write("\t\t");

		String name;
		email = (String)hs.getAttribute("email");
		if (email == null) {
			name = "My Account";
		}
		else {
			name = email;
			name = name.substring(0, name.lastIndexOf("@"));
		}
		
      out.write("\n");
      out.write("\t\t<a href=\"login.jsp\"> <span class=\"glyphicon glyphicon-user user1\"\n");
      out.write("\t\t\tstyle=\"color: blue; font-size: 22px;\"></span>\n");
      out.write("\t\t\t<p class=\"account\" style=\"font-size: 22px; color: blue;\">My\n");
      out.write("\t\t\t\tAccount</p>\n");
      out.write("\t\t</a>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"container tablediv\">\n");
      out.write("\t\t<table class=\"table table-striped table-bordered\">\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td align=\"center\" style=\"font-size: 18px;\"><span\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-home\"\n");
      out.write("\t\t\t\t\tstyle=\"color: blue; font-size: 40px;\"></span> <br> Real Estate\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t\t<td align=\"center\" style=\"font-size: 18px;\"><span\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-headphones\"\n");
      out.write("\t\t\t\t\tstyle=\"color: blue; font-size: 40px;\"></span> <br>\n");
      out.write("\t\t\t\t\tEntertainment</td>\n");
      out.write("\t\t\t\t<td align=\"center\" style=\"font-size: 18px;\"><span\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-facetime-video\"\n");
      out.write("\t\t\t\t\tstyle=\"color: blue; font-size: 40px;\"></span> <br> Videos</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td align=\"center\" style=\"font-size: 18px;\"><span\n");
      out.write("\t\t\t\t\tclass=\" glyphicon glyphicon-phone\"\n");
      out.write("\t\t\t\t\tstyle=\"color: blue; font-size: 40px;\"></span> <br> Mobiles &\n");
      out.write("\t\t\t\t\tTablets</td>\n");
      out.write("\t\t\t\t<td align=\"center\" style=\"font-size: 18px;\"><span\n");
      out.write("\t\t\t\t\tclass=\" glyphicon glyphicon-book\"\n");
      out.write("\t\t\t\t\tstyle=\"color: blue; font-size: 40px;\"></span> <br> Books</td>\n");
      out.write("\t\t\t\t<td align=\"center\" style=\"font-size: 18px;\"><span\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-camera\"\n");
      out.write("\t\t\t\t\tstyle=\"color: blue; font-size: 40px;\"></span> <br> Cameras</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td align=\"center\" style=\"font-size: 18px;\"><span\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-bed\"\n");
      out.write("\t\t\t\t\tstyle=\"color: blue; font-size: 40px;\"></span> <br> Furnitures\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t\t<td align=\"center\" style=\"font-size: 18px;\"><span\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-lamp\"\n");
      out.write("\t\t\t\t\tstyle=\"color: blue; font-size: 40px;\"></span> <br> Interiors</td>\n");
      out.write("\t\t\t\t<td align=\"center\" style=\"font-size: 18px;\"><span\n");
      out.write("\t\t\t\t\tclass=\" glyphicon glyphicon-pencil\"\n");
      out.write("\t\t\t\t\tstyle=\"color: blue; font-size: 40px;\"></span> <br>\n");
      out.write("\t\t\t\t\tStationaries</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</table>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
